### ISSUE TITLE
Create blog section using sphinx

### ISSUE THREAD

**Issue by xmnlab** [plures/xnd-all#10]
assigned to @andersy005

**Comment by xmnlab** [comment]
@saulshanabrook 

could the blog be on xnd.io (webpage repo) ?

**Comment by andersy005** [comment]
@saulshanabrook, do you have any recommendation on other Python projects that have blog posts that we could emulated or use as a reference? 

If not, any recommendations on templates that we could use for this blog are welcome too!

**Comment by saulshanabrook** [comment]
We could so it on xnd-website with jykell, whitch GitHub supports. But
recently I was thinking maybe it would be better to do it in Sphinx, so we
only have one build system to deal with and could do it in xnd-all. I was
looking at http://ablog.readthedocs.io/

**Comment by xmnlab** [comment]
@saulshanabrook that sounds good to me.

**Comment by andersy005** [comment]
@saulshanabrook, @skrah 
I found http://sunpy.org/ when I was looking for some references for creating a blog section for xnd.io. Ivan and I had a discussion about  how great their website is developed.  The entire website is built with sphinx. What are your thoughts? Would it be worthwhile to emulate what sunpy does for xnd.io? 

Here are some extra references:
- https://github.com/sunpy/sunpy.org
- https://github.com/sunpy/sunpy-sphinx-theme

**Comment by xmnlab** [comment]
@andersy005 also shared with me this link: http://sunpy.org/posts/2018/2018-07-21-coronal-loop-coordinates.html

it is a very nice blogpost with a link (at the top) to binder it is a very easy way to have the tutorial/blog-post statically and offer a option to play with that.

**Comment by saulshanabrook** [comment]
That looks like a great reference! Their blog looks very nice.

**Comment by xmnlab** [comment]
@saulshanabrook @skrah 

Ok, so we will move in this direction. let us know if you have any concern or recommendation.

**Comment by rgommers** [comment]
I think we should close this. In general blogs are a time sink for individual projects, because once you have one you're sort of forced to write something once in a while. So it's probably better to write on the Labs blog occasionally (talking about new features/releases when that makes sense), and leave the XND site for non time-stamped content.

**Comment by xmnlab** [comment]
sounds good to me!
