### ISSUE TITLE
Add CONTRIBUTING.txt for each plures project

### ISSUE THREAD

**Issue by xmnlab** [plures/xnd-all#15]

**Comment by xmnlab** [comment]
As we have talked in internal channel. I add this to you. I will quote here the last thing we talked:

> @xmnlab I'll write `CONTRIBUTING.txt`.  Due to the nature of subtrees, the "upstream" packages are still `ndtypes`, `xnd`, `gumath` and `xndtools`, so development (except for the xnd docs) happens there.
Changes should be merged into `xnd-all` when "upstream" is considered to be in a good and coherent state.  I guess that would be for me to decide for `xnd` and for Pearu for `xndtools`.

Let me know if I can help with anything. If you have a template or a description for one library I can replicate to the others.

**Comment by skrah** [comment]
I've added CONTRIBUTING.txt to `xnd-all`.  It seems to me that contributing to the individual upstream packages is obvious (standard GitHub procedure), so they don't need instructions.
