### ISSUE TITLE
Add Travis CI and AppVeyour badges to README.md

### ISSUE THREAD

**Issue by pearu** [plures/xnd-all#20]
For Travis CI, the following entry should work:
```
[![Travis CI Build Status](https://travis-ci.org/plures/xnd-all.svg?branch=master)](https://travis-ci.org/plures/xnd-all)
```
For AppVeyour, use
```
[![AppVeyor Build status](https://ci.appveyor.com/api/projects/status/<XYZ>/branch/master?svg=true)](https://ci.appveyor.com/project/<OWNER>/xnd-all/branch/master)
```
where `<XYZ>` and `<OWNER>` should be replaced. The easiest way would be to just copy the entry from AppVeyour configuration page, see Badges.

**Comment by skrah** [comment]
Done, this is a good idea.  Actually there are two appveyor builds -- the conda build didn't have a webhook, so it was invisible in PRs.  But I added that now (I think there's one link issue with the xndtools Windows conda build).
