### ISSUE TITLE
xnd-all install of xndtools does not create xndtools directory in site-packages

### ISSUE THREAD

**Issue by mpeaton** [plures/xnd-all#27]
xndtools getting started guide:
https://xnd.readthedocs.io/en/latest/xndtools/tutorials/getting_started.html

lists the xndtools/kernel_generator directory for library locations, but this directory was not generated by setup.py on my system.  

site-packages/xndtools-0.2.0.dev3-py3.6-macosx-10.9-x86_64.egg

exists

**Comment by skrah** [comment]
You mean this line?

```
-I$SITE_PACKAGES/xndtools/kernel_generator
```

Yes, on my system it is also in `xndtools-0.2.0.dev3-py3.8-linux-x86_64.egg/xndtools/kernel_generator/`.

This sort of thing is why I still use plain `distutils` and no `setuptools` for `ndtypes`, `xnd` and `gumath`.

**Comment by skrah** [comment]
Should be fixed in 0a367bbed5cefe887df4e714995555e87e8b1f9c.
