### ISSUE TITLE
Testing Ruby bindings in CI

### ISSUE THREAD

**Issue by rgommers** [plures/xnd-all#32]
There's a separate `xnd-ruby` repo now, and it would be useful to know when changes in `xnd`, `gumath` or `ndtypes` break something in `xnd-ruby`. So pulling that in and running tests in the CI of this repo would be useful. 

Long-term it's probably better (more scalable) to only test master branches of `xnd`, `gumath` or `ndtypes` in the `xnd-ruby` CI, but for now it's likely to be a lower-activity repo so the feedback loop may be too long.

**Comment by skrah** [comment]
I think that is currently not sustainable.  The `xnd-all` CIs build and upload the `conda` `dev` packages only if the build succeeds.  Also, I need to see a green CI and not look at details.

Currently it will be a fact of life that Ruby will be broken repeatedly.  I suggest instead for `xnd-ruby` to focus on a particular revision, get that stable and bump to the next revision after a couple of months.

@v0dro

**Comment by rgommers** [comment]
Yes fair enough, green CI is needed. Could be done in several ways, perhaps triggering a daily CI run in `xnd-ruby` against XND master. Or a separate repo with dedicated CI. Or a `failure-allowed` CI run here.

> focus on a particular revision, get that stable and bump to the next revision after a couple of months.

Let's see what @v0dro thinks of that. I think it's harder to pinpoint the cause of breakage (and corresponding fix) after a long time than if it's visible straight away though.

**Comment by skrah** [comment]
Sure, `xnd-ruby` should have its own CI. There @v0dro should just either pull in the most recent `xnd-all` or pin a revision.  He'll find out what works best.
